# Generated by Django 5.0.6 on 2024-06-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_List',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
