# Generated by Django 5.0.6 on 2024-06-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_supplier_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('Warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('manager_name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse')),
            ],
        ),
    ]
