# Generated by Django 5.0.6 on 2024-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_warehouse_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='Warehouse_id',
            new_name='warehouse_id',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
