# Generated by Django 5.0.6 on 2024-06-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_warehouse_id_warehouse_warehouse_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('warehouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse')),
            ],
        ),
    ]
