# Generated by Django 5.0.6 on 2024-06-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter a strong password', max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_cost', to='main.order')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_quantity', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='SalesList',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
